// <auto-generated />
using System;
using System.Collections.Generic;
using MapDbContextLib.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MillimanAccessPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:Enum:authentication_type", "default,ws_federation")
                .HasAnnotation("Npgsql:Enum:content_type_enum", "unknown,qlikview,html,pdf,file_download,power_bi")
                .HasAnnotation("Npgsql:Enum:publication_status", "unknown,canceled,rejected,validating,queued,processing,post_process_ready,post_processing,processed,confirming,confirmed,replaced,error")
                .HasAnnotation("Npgsql:Enum:reduction_status_enum", "unspecified,canceled,rejected,validating,queued,reducing,reduced,live,replaced,warning,error")
                .HasAnnotation("Npgsql:PostgresExtension:citext", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MapDbContextLib.Context.AuthenticationScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("DisplayName");

                    b.Property<List<string>>("DomainList")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("SchemeProperties")
                        .HasColumnType("jsonb");

                    b.Property<AuthenticationType>("Type");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("AuthenticationScheme");
                });

            modelBuilder.Entity("MapDbContextLib.Context.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<List<string>>("AcceptedEmailAddressExceptionList")
                        .IsRequired();

                    b.Property<List<string>>("AcceptedEmailDomainList")
                        .IsRequired();

                    b.Property<string>("ClientCode");

                    b.Property<string>("ConsultantEmail");

                    b.Property<string>("ConsultantName");

                    b.Property<string>("ConsultantOffice");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactName");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("ContactTitle");

                    b.Property<int>("DomainListCountLimit")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(3);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NewUserWelcomeText");

                    b.Property<Guid?>("ParentClientId");

                    b.Property<Guid>("ProfitCenterId");

                    b.HasKey("Id");

                    b.HasIndex("ParentClientId");

                    b.HasIndex("ProfitCenterId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentPublicationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ApplicationUserId");

                    b.Property<DateTime>("CreateDateTimeUtc");

                    b.Property<string>("LiveReadyAssociatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("LiveReadyFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("OutcomeMetadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ReductionRelatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<PublicationStatus>("RequestStatus");

                    b.Property<string>("RequestedAssociatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultHierarchy")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RootContentItemId");

                    b.Property<string>("StatusMessage");

                    b.Property<string>("UploadedRelatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RootContentItemId");

                    b.ToTable("ContentPublicationRequest");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentReductionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ApplicationUserId");

                    b.Property<Guid?>("ContentPublicationRequestId");

                    b.Property<DateTime>("CreateDateTimeUtc");

                    b.Property<string>("MasterContentChecksum");

                    b.Property<string>("MasterContentHierarchy")
                        .HasColumnType("jsonb");

                    b.Property<string>("MasterFilePath")
                        .IsRequired();

                    b.Property<string>("OutcomeMetadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ProcessingStartDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

                    b.Property<string>("ReducedContentChecksum");

                    b.Property<string>("ReducedContentHierarchy")
                        .HasColumnType("jsonb");

                    b.Property<ReductionStatusEnum>("ReductionStatus")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(ReductionStatusEnum.Unspecified);

                    b.Property<string>("ReductionStatusMessage");

                    b.Property<string>("ResultFilePath");

                    b.Property<string>("SelectionCriteria")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SelectionGroupId");

                    b.Property<int>("TaskAction");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ContentPublicationRequestId");

                    b.HasIndex("SelectionGroupId");

                    b.ToTable("ContentReductionTask");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("CanReduce");

                    b.Property<string>("DefaultIconName")
                        .IsRequired();

                    b.Property<List<string>>("FileExtensions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ContentType");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDrop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ClientId");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RootPath")
                        .IsUnique();

                    b.ToTable("FileDrop");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedByAccountId");

                    b.Property<string>("Description");

                    b.Property<Guid>("FileDropId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid?>("ParentDirectoryId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("FileDropId");

                    b.HasIndex("ParentDirectoryId");

                    b.ToTable("FileDropDirectory");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedByAccountId");

                    b.Property<string>("Description");

                    b.Property<Guid>("DirectoryId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("DirectoryId");

                    b.ToTable("FileDropFile");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropUserPermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("DeleteAccess");

                    b.Property<Guid>("FileDropId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("ReadAccess");

                    b.Property<bool>("WriteAccess");

                    b.HasKey("Id");

                    b.HasIndex("FileDropId");

                    b.ToTable("FileDropUserPermissionGroup");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Checksum");

                    b.Property<string>("ClientFileIdentifier")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDateTimeUtc");

                    b.Property<DateTime>("InitiatedDateTimeUtc");

                    b.Property<int>("Status");

                    b.Property<string>("StatusMessage");

                    b.Property<string>("StoragePath");

                    b.HasKey("Id");

                    b.ToTable("FileUpload");
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("FieldDelimiter");

                    b.Property<string>("FieldDisplayName")
                        .IsRequired();

                    b.Property<string>("FieldName")
                        .IsRequired();

                    b.Property<Guid>("RootContentItemId");

                    b.Property<int>("StructureType")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("RootContentItemId");

                    b.ToTable("HierarchyField");
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("HierarchyFieldId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("HierarchyFieldId");

                    b.ToTable("HierarchyFieldValue");
                });

            modelBuilder.Entity("MapDbContextLib.Context.NameValueConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("");

                    b.HasKey("Key");

                    b.ToTable("NameValueConfiguration");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ProfitCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactName");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("ContactTitle");

                    b.Property<string>("MillimanOffice");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ProfitCenterCode");

                    b.HasKey("Id");

                    b.ToTable("ProfitCenter");
                });

            modelBuilder.Entity("MapDbContextLib.Context.RootContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AssociatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ClientId");

                    b.Property<string>("ContentDisclaimer");

                    b.Property<string>("ContentFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("ContentName")
                        .IsRequired();

                    b.Property<Guid>("ContentTypeId");

                    b.Property<string>("Description");

                    b.Property<bool>("DoesReduce");

                    b.Property<bool>("IsSuspended");

                    b.Property<string>("Notes");

                    b.Property<string>("TypeSpecificDetail")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContentTypeId");

                    b.ToTable("RootContentItem");
                });

            modelBuilder.Entity("MapDbContextLib.Context.SelectionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ContentInstanceUrl");

                    b.Property<string>("GroupName")
                        .IsRequired();

                    b.Property<bool>("IsMaster");

                    b.Property<bool>("IsSuspended");

                    b.Property<string>("ReducedContentChecksum");

                    b.Property<Guid>("RootContentItemId");

                    b.Property<Guid[]>("SelectedHierarchyFieldValueList");

                    b.HasKey("Id");

                    b.HasIndex("RootContentItemId");

                    b.ToTable("SelectionGroup");
                });

            modelBuilder.Entity("MapDbContextLib.Context.SftpAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("ApplicationUserId");

                    b.Property<Guid>("FileDropId");

                    b.Property<Guid?>("FileDropUserPermissionGroupId");

                    b.Property<string>("PasswordHash");

                    b.Property<DateTime>("PasswordResetDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("FileDropId");

                    b.HasIndex("FileDropUserPermissionGroupId");

                    b.ToTable("SftpAccount");
                });

            modelBuilder.Entity("MapDbContextLib.Context.SftpConnection", b =>
                {
                    b.Property<string>("Id");

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<DateTime>("LastActivityUtc")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("MetaData")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SftpAccountId");

                    b.HasKey("Id");

                    b.HasIndex("SftpAccountId");

                    b.ToTable("SftpConnection");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserInSelectionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("DisclaimerAccepted");

                    b.Property<Guid>("SelectionGroupId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SelectionGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInSelectionGroup");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ClientId");

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleInClient");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInProfitCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ProfitCenterId");

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProfitCenterId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleInProfitCenter");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInRootContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("RootContentItemId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("RootContentItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleInRootContentItem");
                });

            modelBuilder.Entity("MapDbContextLib.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<int>("RoleEnum");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("MapDbContextLib.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("AccessFailedCount");

                    b.Property<Guid?>("AuthenticationSchemeId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Employer");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsSuspended");

                    b.Property<bool?>("IsUserAgreementAccepted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(null);

                    b.Property<string>("LastName");

                    b.Property<DateTime>("LastPasswordChangeDateTimeUtc");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PreviousPasswords")
                        .HasColumnType("jsonb");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("AuthenticationSchemeId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MapDbContextLib.Context.Client", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "ParentClient")
                        .WithMany()
                        .HasForeignKey("ParentClientId");

                    b.HasOne("MapDbContextLib.Context.ProfitCenter", "ProfitCenter")
                        .WithMany()
                        .HasForeignKey("ProfitCenterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentPublicationRequest", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentReductionTask", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.ContentPublicationRequest", "ContentPublicationRequest")
                        .WithMany()
                        .HasForeignKey("ContentPublicationRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.SelectionGroup", "SelectionGroup")
                        .WithMany()
                        .HasForeignKey("SelectionGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDrop", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropDirectory", b =>
                {
                    b.HasOne("MapDbContextLib.Context.SftpAccount", "CreatedByAccount")
                        .WithMany("Directories")
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.FileDrop", "FileDrop")
                        .WithMany()
                        .HasForeignKey("FileDropId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.FileDropDirectory", "ParentDirectoryEntry")
                        .WithMany("ChildDirectories")
                        .HasForeignKey("ParentDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropFile", b =>
                {
                    b.HasOne("MapDbContextLib.Context.SftpAccount", "CreatedByAccount")
                        .WithMany("Files")
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MapDbContextLib.Context.FileDropDirectory", "Directory")
                        .WithMany("Files")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropUserPermissionGroup", b =>
                {
                    b.HasOne("MapDbContextLib.Context.FileDrop", "FileDrop")
                        .WithMany()
                        .HasForeignKey("FileDropId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyField", b =>
                {
                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyFieldValue", b =>
                {
                    b.HasOne("MapDbContextLib.Context.HierarchyField", "HierarchyField")
                        .WithMany()
                        .HasForeignKey("HierarchyFieldId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.RootContentItem", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.SelectionGroup", b =>
                {
                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.SftpAccount", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("SftpAccounts")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.FileDrop", "FileDrop")
                        .WithMany("SftpAccounts")
                        .HasForeignKey("FileDropId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.FileDropUserPermissionGroup", "FileDropUserPermissionGroup")
                        .WithMany()
                        .HasForeignKey("FileDropUserPermissionGroupId");
                });

            modelBuilder.Entity("MapDbContextLib.Context.SftpConnection", b =>
                {
                    b.HasOne("MapDbContextLib.Context.FileDrop", "SftpAccount")
                        .WithMany()
                        .HasForeignKey("SftpAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserInSelectionGroup", b =>
                {
                    b.HasOne("MapDbContextLib.Context.SelectionGroup", "SelectionGroup")
                        .WithMany()
                        .HasForeignKey("SelectionGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInClient", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInProfitCenter", b =>
                {
                    b.HasOne("MapDbContextLib.Context.ProfitCenter", "ProfitCenter")
                        .WithMany()
                        .HasForeignKey("ProfitCenterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInRootContentItem", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Identity.ApplicationUser", b =>
                {
                    b.HasOne("MapDbContextLib.Context.AuthenticationScheme", "AuthenticationScheme")
                        .WithMany()
                        .HasForeignKey("AuthenticationSchemeId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
