// <auto-generated />
using MapDbContextLib.Context;
using MapDbContextLib.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MillimanAccessPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("MapDbContextLib.Context.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string[]>("AcceptedEmailAddressExceptionList");

                    b.Property<string[]>("AcceptedEmailDomainList")
                        .IsRequired();

                    b.Property<string>("ClientCode");

                    b.Property<string>("ConsultantEmail");

                    b.Property<string>("ConsultantName");

                    b.Property<string>("ConsultantOffice");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactName");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("ContactTitle");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<long?>("ParentClientId");

                    b.Property<long>("ProfitCenterId");

                    b.HasKey("Id");

                    b.HasIndex("ParentClientId");

                    b.HasIndex("ProfitCenterId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentPublicationRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ApplicationUserId");

                    b.Property<DateTime>("CreateDateTimeUtc");

                    b.Property<string>("LiveReadyFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("ReductionRelatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<int>("RequestStatus");

                    b.Property<string>("ResultHierarchy")
                        .HasColumnType("jsonb");

                    b.Property<long>("RootContentItemId");

                    b.Property<string>("StatusMessage");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RootContentItemId");

                    b.ToTable("ContentPublicationRequest");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentReductionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<long>("ApplicationUserId");

                    b.Property<long?>("ContentPublicationRequestId");

                    b.Property<DateTime>("CreateDateTimeUtc");

                    b.Property<string>("MasterContentChecksum");

                    b.Property<string>("MasterContentHierarchy")
                        .HasColumnType("jsonb");

                    b.Property<string>("MasterFilePath")
                        .IsRequired();

                    b.Property<string>("ReducedContentChecksum");

                    b.Property<string>("ReducedContentHierarchy")
                        .HasColumnType("jsonb");

                    b.Property<long>("ReductionStatus")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0L);

                    b.Property<string>("ReductionStatusMessage");

                    b.Property<string>("ResultFilePath");

                    b.Property<string>("SelectionCriteria")
                        .HasColumnType("jsonb");

                    b.Property<long>("SelectionGroupId");

                    b.Property<int>("TaskAction");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ContentPublicationRequestId");

                    b.HasIndex("SelectionGroupId");

                    b.ToTable("ContentReductionTask");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CanReduce");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ContentType");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Checksum")
                        .IsRequired();

                    b.Property<string>("ClientFileIdentifier")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDateTimeUtc");

                    b.Property<string>("StoragePath")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("FileUpload");
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FieldDelimiter");

                    b.Property<string>("FieldDisplayName")
                        .IsRequired();

                    b.Property<string>("FieldName")
                        .IsRequired();

                    b.Property<long>("RootContentItemId");

                    b.Property<int>("StructureType")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("RootContentItemId");

                    b.ToTable("HierarchyField");
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyFieldValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("HierarchyFieldId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("HierarchyFieldId");

                    b.ToTable("HierarchyFieldValue");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ProfitCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactName");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("ContactTitle");

                    b.Property<string>("MillimanOffice");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ProfitCenterCode");

                    b.HasKey("Id");

                    b.ToTable("ProfitCenter");
                });

            modelBuilder.Entity("MapDbContextLib.Context.RootContentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ClientId");

                    b.Property<string>("ContentFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("ContentName")
                        .IsRequired();

                    b.Property<long>("ContentTypeId");

                    b.Property<string>("Description");

                    b.Property<bool>("DoesReduce");

                    b.Property<string>("Notes");

                    b.Property<string>("TypeSpecificDetail")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContentTypeId");

                    b.ToTable("RootContentItem");
                });

            modelBuilder.Entity("MapDbContextLib.Context.SelectionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentInstanceUrl");

                    b.Property<string>("GroupName")
                        .IsRequired();

                    b.Property<bool>("IsMaster");

                    b.Property<long>("RootContentItemId");

                    b.Property<long[]>("SelectedHierarchyFieldValueList");

                    b.HasKey("Id");

                    b.HasIndex("RootContentItemId");

                    b.ToTable("SelectionGroup");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserInSelectionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("SelectionGroupId");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SelectionGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInSelectionGroup");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInClient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ClientId");

                    b.Property<long>("RoleId");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleInClient");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInProfitCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ProfitCenterId");

                    b.Property<long>("RoleId");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProfitCenterId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleInProfitCenter");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInRootContentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("RoleId");

                    b.Property<long>("RootContentItemId");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("RootContentItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleInRootContentItem");
                });

            modelBuilder.Entity("MapDbContextLib.Identity.ApplicationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("MapDbContextLib.Identity.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Employer");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<long>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<long>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MapDbContextLib.Context.Client", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "ParentClient")
                        .WithMany()
                        .HasForeignKey("ParentClientId");

                    b.HasOne("MapDbContextLib.Context.ProfitCenter", "ProfitCenter")
                        .WithMany()
                        .HasForeignKey("ProfitCenterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentPublicationRequest", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentReductionTask", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.ContentPublicationRequest", "ContentPublicationRequest")
                        .WithMany()
                        .HasForeignKey("ContentPublicationRequestId");

                    b.HasOne("MapDbContextLib.Context.SelectionGroup", "SelectionGroup")
                        .WithMany()
                        .HasForeignKey("SelectionGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyField", b =>
                {
                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyFieldValue", b =>
                {
                    b.HasOne("MapDbContextLib.Context.HierarchyField", "HierarchyField")
                        .WithMany()
                        .HasForeignKey("HierarchyFieldId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.RootContentItem", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.SelectionGroup", b =>
                {
                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserInSelectionGroup", b =>
                {
                    b.HasOne("MapDbContextLib.Context.SelectionGroup", "SelectionGroup")
                        .WithMany()
                        .HasForeignKey("SelectionGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInClient", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInProfitCenter", b =>
                {
                    b.HasOne("MapDbContextLib.Context.ProfitCenter", "ProfitCenter")
                        .WithMany()
                        .HasForeignKey("ProfitCenterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInRootContentItem", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
