// <auto-generated />
using System;
using System.Collections.Generic;
using MapDbContextLib.Context;
using MapDbContextLib.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MillimanAccessPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:Enum:authentication_type", "default,ws_federation")
                .HasAnnotation("Npgsql:Enum:content_type_enum", "unknown,qlikview,html,pdf,file_download,power_bi")
                .HasAnnotation("Npgsql:Enum:file_drop_notification_type", "file_write,file_read,file_delete")
                .HasAnnotation("Npgsql:Enum:publication_status", "unknown,canceled,rejected,validating,queued,processing,post_process_ready,post_processing,processed,confirming,confirmed,replaced,error")
                .HasAnnotation("Npgsql:Enum:reduction_status_enum", "unspecified,canceled,rejected,validating,queued,reducing,reduced,live,replaced,warning,error")
                .HasAnnotation("Npgsql:PostgresExtension:citext", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MapDbContextLib.Context.AuthenticationScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<List<string>>("DomainList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemeProperties")
                        .HasColumnType("jsonb");

                    b.Property<AuthenticationType>("Type")
                        .HasColumnType("authentication_type");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("AuthenticationScheme");
                });

            modelBuilder.Entity("MapDbContextLib.Context.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<List<string>>("AcceptedEmailAddressExceptionList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("AcceptedEmailDomainList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ClientCode")
                        .HasColumnType("text");

                    b.Property<string>("ConsultantEmail")
                        .HasColumnType("text");

                    b.Property<string>("ConsultantName")
                        .HasColumnType("text");

                    b.Property<string>("ConsultantOffice")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("text");

                    b.Property<int>("DomainListCountLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<ClientAccessReview>("LastAccessReview")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("jsonb_build_object('UserName', 'N/A', 'LastReviewDateTimeUtc', now() at time zone 'utc')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewUserWelcomeText")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfitCenterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentClientId");

                    b.HasIndex("ProfitCenterId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentPublicationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDateTimeUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LiveReadyAssociatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("LiveReadyFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("OutcomeMetadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ReductionRelatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<PublicationStatus>("RequestStatus")
                        .HasColumnType("publication_status");

                    b.Property<string>("RequestedAssociatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultHierarchy")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RootContentItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("text");

                    b.Property<string>("UploadedRelatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RootContentItemId");

                    b.ToTable("ContentPublicationRequest");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentReductionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContentPublicationRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDateTimeUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MasterContentChecksum")
                        .HasColumnType("text");

                    b.Property<string>("MasterContentHierarchy")
                        .HasColumnType("jsonb");

                    b.Property<string>("MasterFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutcomeMetadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ProcessingStartDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

                    b.Property<string>("ReducedContentChecksum")
                        .HasColumnType("text");

                    b.Property<string>("ReducedContentHierarchy")
                        .HasColumnType("jsonb");

                    b.Property<ReductionStatusEnum>("ReductionStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("reduction_status_enum")
                        .HasDefaultValue(ReductionStatusEnum.Unspecified);

                    b.Property<string>("ReductionStatusMessage")
                        .HasColumnType("text");

                    b.Property<string>("ResultFilePath")
                        .HasColumnType("text");

                    b.Property<string>("SelectionCriteria")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SelectionGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskAction")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ContentPublicationRequestId");

                    b.HasIndex("SelectionGroupId");

                    b.ToTable("ContentReductionTask");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("CanReduce")
                        .HasColumnType("boolean");

                    b.Property<string>("DefaultIconName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("FileExtensions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'");

                    b.Property<ContentTypeEnum>("TypeEnum")
                        .HasColumnType("content_type_enum");

                    b.HasKey("Id");

                    b.ToTable("ContentType");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDrop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("ShortHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RootPath")
                        .IsUnique();

                    b.HasIndex("ShortHash")
                        .IsUnique();

                    b.ToTable("FileDrop");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CanonicalFileDropPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FileDropId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentDirectoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentDirectoryId");

                    b.HasIndex("FileDropId", "CanonicalFileDropPath")
                        .IsUnique();

                    b.ToTable("FileDropDirectory");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DirectoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UploadDateTimeUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("DirectoryId", "FileName")
                        .IsUnique();

                    b.ToTable("FileDropFile");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropUserPermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("DeleteAccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FileDropId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPersonalGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReadAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("WriteAccess")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FileDropId");

                    b.ToTable("FileDropUserPermissionGroup");
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Checksum")
                        .HasColumnType("text");

                    b.Property<string>("ClientFileIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("InitiatedDateTimeUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileUpload");
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("FieldDelimiter")
                        .HasColumnType("text");

                    b.Property<string>("FieldDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RootContentItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("StructureType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("RootContentItemId");

                    b.ToTable("HierarchyField");
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("HierarchyFieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyFieldId");

                    b.ToTable("HierarchyFieldValue");
                });

            modelBuilder.Entity("MapDbContextLib.Context.NameValueConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.HasKey("Key");

                    b.ToTable("NameValueConfiguration");
                });

            modelBuilder.Entity("MapDbContextLib.Context.ProfitCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("text");

                    b.Property<string>("MillimanOffice")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfitCenterCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProfitCenter");
                });

            modelBuilder.Entity("MapDbContextLib.Context.RootContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AssociatedFiles")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentDisclaimer")
                        .HasColumnType("text");

                    b.Property<string>("ContentFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("ContentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("DoesReduce")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("TypeSpecificDetail")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContentTypeId");

                    b.ToTable("RootContentItem");
                });

            modelBuilder.Entity("MapDbContextLib.Context.SelectionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ContentInstanceUrl")
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<string>("ReducedContentChecksum")
                        .HasColumnType("text");

                    b.Property<Guid>("RootContentItemId")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("SelectedHierarchyFieldValueList")
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.HasIndex("RootContentItemId");

                    b.ToTable("SelectionGroup");
                });

            modelBuilder.Entity("MapDbContextLib.Context.SftpAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileDropId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FileDropUserPermissionGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<HashSet<FileDropUserNotificationModel>>("NotificationSubscriptions")
                        .HasColumnType("jsonb");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("PasswordResetDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("FileDropId");

                    b.HasIndex("FileDropUserPermissionGroupId");

                    b.ToTable("SftpAccount");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserInSelectionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("DisclaimerAccepted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SelectionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SelectionGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInSelectionGroup");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleInClient");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInProfitCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ProfitCenterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfitCenterId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleInProfitCenter");
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInRootContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RootContentItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("RootContentItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleInRootContentItem");
                });

            modelBuilder.Entity("MapDbContextLib.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<int>("RoleEnum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("MapDbContextLib.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AuthenticationSchemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Employer")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsUserAgreementAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(null);

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastPasswordChangeDateTimeUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreviousPasswords")
                        .HasColumnType("jsonb");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("AuthenticationSchemeId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MapDbContextLib.Context.Client", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "ParentClient")
                        .WithMany()
                        .HasForeignKey("ParentClientId");

                    b.HasOne("MapDbContextLib.Context.ProfitCenter", "ProfitCenter")
                        .WithMany()
                        .HasForeignKey("ProfitCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentPublicationRequest", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.ContentReductionTask", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Context.ContentPublicationRequest", "ContentPublicationRequest")
                        .WithMany()
                        .HasForeignKey("ContentPublicationRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.SelectionGroup", "SelectionGroup")
                        .WithMany()
                        .HasForeignKey("SelectionGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDrop", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropDirectory", b =>
                {
                    b.HasOne("MapDbContextLib.Context.FileDrop", "FileDrop")
                        .WithMany()
                        .HasForeignKey("FileDropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Context.FileDropDirectory", "ParentDirectory")
                        .WithMany("ChildDirectories")
                        .HasForeignKey("ParentDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropFile", b =>
                {
                    b.HasOne("MapDbContextLib.Context.SftpAccount", "CreatedByAccount")
                        .WithMany("Files")
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Context.FileDropDirectory", "Directory")
                        .WithMany("Files")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.FileDropUserPermissionGroup", b =>
                {
                    b.HasOne("MapDbContextLib.Context.FileDrop", "FileDrop")
                        .WithMany()
                        .HasForeignKey("FileDropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyField", b =>
                {
                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.HierarchyFieldValue", b =>
                {
                    b.HasOne("MapDbContextLib.Context.HierarchyField", "HierarchyField")
                        .WithMany()
                        .HasForeignKey("HierarchyFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.RootContentItem", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Context.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.SelectionGroup", b =>
                {
                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.SftpAccount", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("SftpAccounts")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapDbContextLib.Context.FileDrop", "FileDrop")
                        .WithMany("SftpAccounts")
                        .HasForeignKey("FileDropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Context.FileDropUserPermissionGroup", "FileDropUserPermissionGroup")
                        .WithMany("SftpAccounts")
                        .HasForeignKey("FileDropUserPermissionGroupId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserInSelectionGroup", b =>
                {
                    b.HasOne("MapDbContextLib.Context.SelectionGroup", "SelectionGroup")
                        .WithMany()
                        .HasForeignKey("SelectionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInClient", b =>
                {
                    b.HasOne("MapDbContextLib.Context.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInProfitCenter", b =>
                {
                    b.HasOne("MapDbContextLib.Context.ProfitCenter", "ProfitCenter")
                        .WithMany()
                        .HasForeignKey("ProfitCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Context.UserRoleInRootContentItem", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Context.RootContentItem", "RootContentItem")
                        .WithMany()
                        .HasForeignKey("RootContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapDbContextLib.Identity.ApplicationUser", b =>
                {
                    b.HasOne("MapDbContextLib.Context.AuthenticationScheme", "AuthenticationScheme")
                        .WithMany()
                        .HasForeignKey("AuthenticationSchemeId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MapDbContextLib.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
