FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine as build-env

WORKDIR /app

RUN dotnet tool install --tool-path ./ dotnet-certificate-tool

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-alpine

COPY --from=build-env /app /app

ARG ASPNETCORE_ENVIRONMENT=CI
ENV ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT

COPY SftpServer/SftpServer/bin/Debug/netcoreapp3.1/* /app/
COPY SftpServer/SftpServerLib/*.json /app/
COPY UtilityScripts/startsftpserver.sh /app/

ENTRYPOINT ["/bin/sh", "/app/startsftpserver.sh"]
